### ISSUE TITLE
Tree types of paths - relative, absolute and canonical

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/path#112]
What about the idea to have tree types of paths - **relative**, **absolute** and **canonical**? **Canonical** could be used for paths equality and **absolute** to be used for actual directory/file operations. **Absolute** paths will be relative to root (Linux) or drive (Windows) and will not follow symbolic links (Linux), directory junctions and substitutions (Windows).

Related discussion and explanation: https://github.com/commercialhaskell/stack/issues/3442

**Comment by joehillen** [comment]
This sounds like an idea to test out in a new library. The path library is not large or difficult, so it would not be hard to replicate its functionality in a new package.

**Comment by varosi** [comment]
Yes, it's not difficult. But it will be yet another path library and the idea is this to be used in Stack tool. Currently there is a great issue under Windows about it. And this library will be even more precise and correct.

**Comment by joehillen** [comment]
Feel free to open a PR.

**Comment by joehillen** [comment]
This sounds like it would require a complete rewrite of the library and its consumers, which I don't think we'd be open to. That's why I think it's an idea worth exploring in another package. stack could use your package instead if that suits them. 

If you don't think this will require any major breaking changes, feel free to open a PR.
