### ISSUE TITLE
A possible bug in stripProperPrefix

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/path#138]
Should it actually return `"."` when the prefix matches actual directory that we're stripping? It seems to me that in that case returning `"."` is the correct behavior because obviously any valid path is a proper prefix of itself. Am I missing something?

Related to mrkkrp/path-io#39

**Comment by harendra-kumar** [comment]
A path is not a "proper" prefix of itself, proper here means that the prefix cannot be the same as the original name. For directory paths we can try to argue that "x" is implicitly equivalent to "x/.", therefore we can return "." here. But we should note that (1) it is not true for file paths, so we will need to differentiate between file and dir, in the file case we still have to throw an exception (2) it is implicit and therefore may cause confusion.

To differentiate between file and dir case without confusion we can rename the API to `stripAncestor` instead of `stripProperPrefix`. The semantics of `stripAncestor` would be to strip only if the supplied prefix is an ancestor `dir` of the path otherwise throw an exception. That means in case of a file, if the prefix is the same as the file path then it will throw an exception because the prefix is not an ancestor dir. In case of a dir we can return `.` as the supplied path can be considered as ancestor/parent dir of `.`. Also:

* `.` shall be considered an ancestor of itself (`./.` is the same as `.`)
* we will have to rename `isProperPrefixOf` to `isAncestorOf`.
