### ISSUE TITLE
Provide a stricter type for filenames?

### ISSUE THREAD

**Issue by hasufell** [commercialhaskell/path#21]
When using functions that read a directory stream you strictly get only filenames, never paths, which means there is no `/` allowed. When comparing filenames it's convenient to know that it is not a path. It's useful for other cases too where I want to save a pair of filename + anchor directory.

`Path Rel t` does not really give me that guarantee. I wonder if adding another separate type like `Path Fn t` would make sense. But that would probably require to introduce a class that summarizes over `Path Rel t` and `Path Fn t`, because a filename can arguably be treated just as `Path Rel t`. Alternatively there could be a safe conversion function without MonadThrow, since it's proven that a filename is always a valid relative path.

**Comment by chrisdone** [comment]
Hm, I think it could be acceptable. With a straight-forward "lifting" from `Fn` to `Rel`, this wouldn't "pollute" the API or mess with it much. We'd just add a few more parsers and TH constructors.

**Comment by chrisdone** [comment]
From what you described here, feel free to make a PR, I'll probably merge it.

**Comment by sjakobi** [comment]
I kind of like this idea. How about calling the type `Name` instead of `Fn` though? IMHO `Path Name Dir` reads slightly more nicely than `Path Fn Dir`.

This addition would mean that we change the type of `filename` and `dirname`, right!?

@mrkkrp Would `path-io` provide a new variant of `listDir` that returns `Path Name x` instead of `Path Abs x` if this is added?

> But that would probably require to introduce a class that summarizes over Path Rel t and Path Fn t, because a filename can arguably be treated just as Path Rel t. Alternatively there could be a safe conversion function without MonadThrow, since it's proven that a filename is always a valid relative path.

Intuitively I prefer the latter idea. What does everyone else think?

**Comment by chrisdone** [comment]
Agree on `Name`.

**Comment by sjakobi** [comment]
> This addition would mean that we change the type of filename and dirname, right!?

On second thought, if we made a class (or type family like [`Path.IO.RelPath`](http://hackage.haskell.org/package/path-io-1.2.2/docs/Path-IO.html#t:RelPath)?!) we could just add a bit of return type polymorphism to `filename` and `basename` and existing code would continue to work.

Not sure if we want to introduce a type family in `path` though. It's kind of an advanced concept and I don't even really understand them right now.

**Comment by NorfairKing** [comment]
+1 on the concept, no opinion on the implementation yet.

**Comment by chrisdone** [comment]
I'd lean towards not adding a type class generally... @borsboom and I, both early users of the package, preferred to keep all types explicit.

**Comment by mrkkrp** [comment]
OK, I'm going to be that guy who has unpopular opinion. I think we should keep number of path types minimal and it's best to stick to what we already have. The benefits of this new type are not obvious to me. If I wanted to treat file path without slashes differently, I'd create a special wrapper. It's not often I want to do it, and so I'd do it in actual application, not library.

Second, I'm strongly against changing existing types in `path-io`, because it's a huge breaking change and there is no way to make it backward-compatible. `listDir` looks like this:

```haskell
listDir :: (MonadIO m, MonadThrow m)
  => Path b Dir        -- ^ Directory to list
  -> m ([Path Abs Dir], [Path Abs File]) -- ^ Sub-directories and files
```

And there is code (including production code I deal with) that depends of this. Maximum I can do is to add another flavor of wrapper called something like `listDir'` that would return these `Path Name File` thingies, and having many functions that do the same thing but have different types is not very nice, IMO.

Even for function like `findExecutable` which currently take `Path Rel File` and certainly could benefit from the new more precise type, I don't want to break compatibility.

I'd really prefer to keep things simple, that is, to have minimal number of basic path type combinations and from that build something rich, instead of having a lot of ad-hoc types per each possible use-case.

**Comment by chrisdone** [comment]
The content aside, I don't think it's too unpopular an opinion to keep things simple and conserve what we have.

> I'd really prefer to keep things simple, that is, to have minimal number of basic path type combinations and from that build something rich, instead of having a lot of ad-hoc types per each possible use-case.

Good points.

**Comment by hasufell** [comment]
I don't use this library anymore, so I don't have a strong opinion. Just want to say that a __path__ (including a relative one) is a fundamentally different concept than a __filename__. It's not really a random use case to only allow filenames in certain functions. Those are basic guarantees.

**Comment by sjakobi** [comment]
I don't really see how adding this would cause _huge_ breaking changes in `path` and `path-io`. I'm under the impression that this would cause mostly additions and require users to add a few `toRelPath`s here and there.

But I don't want to add anything that doesn't have any users so I'm leaning towards closing this now.

> Just want to say that a path (including a relative one) is a fundamentally different concept than a filename.

I also agree with this statement. In `Rel`, `Abs` and `Name`, one of them isn't like the others.

@hasufell, out of interest, why don't you use `path` anymore?

**Comment by hasufell** [comment]
> why don't you use path anymore?

Because I forked this library, so I can move forward with my own preferences/use cases.

**Comment by sjakobi** [comment]
http://hackage.haskell.org/package/hpath, interesting!

**Comment by mrkkrp** [comment]
What I think is that we need to improve `path` and keep it in good shape to avoid fragmentation of community.

**Comment by chrisdone** [comment]
> EDIT: POSIX-only so far.

I believe this is why `path` using `String` is cross-platform. `ByteString` for speed sounds like a good long-term goal, but it comes with correctness challenges.

**Comment by hasufell** [comment]
> but it comes with correctness challenges.

No, ByteString is chosen because it's the only correct thing (or: the closest to correct until we maybe get the [AbstractFilePath](https://ghc.haskell.org/trac/ghc/wiki/Proposal/AbstractFilePath) proposal implemented in base... filepaths on unix are _bytes_, not strings). String is fundamentally wrong.
Ofc you can hack around encoding issues and so forth and then call it cross-platform. I don't think that improves correctness in any way though.

**Comment by chrisdone** [comment]
Eh, correct for whom? When the [system-filepath](http://hackage.haskell.org/package/system-filepath-0.4.13.4/docs/Filesystem-Path.html#t:FilePath) package (which like your package worked in terms of decoding/encoding ByteStrings) was in use and we were maintaining it and using it in stack, we had to deal with encoding issues all the time, and after GHC 7.4 dealt with encoding issues we [deprecated system-filepath](http://www.yesodweb.com/blog/2015/05/deprecating-system-filepath), as did [its author](https://plus.google.com/+JohnMillikin/posts/j7NCSdRHGvN), later that lead up to the abstract file propsal, which is good but we're not there yet. By using `FilePath` like the rest of the Haskell standard library we are encoding-compatible with them and can defer encoding mess to someone else's problem (which is always nice to do). By using ByteString in your project, you've made it your problem. Good luck to you.

**Comment by NorfairKing** [comment]
> No, ByteString is chosen because it's the only correct thing (or: the closest to correct until we maybe get the AbstractFilePath proposal implemented in base... filepaths on unix are bytes, not strings).

+1, would like to see bytestrings under the hood for POSIX in `path`.

Though that's not the objective of this issue.
