### ISSUE TITLE
Tests fail on Windows!

### ISSUE THREAD

**Issue by athanclark** [commercialhaskell/path#39]
I hate windows!

When you run `stack test` on the fresh clone of commit c9e3aae8 in a windows 10 environment, you'll see (at compile time !!) the build will fail:

![](https://s10.postimg.org/aoogvbvo9/Screenshot_from_2016_10_25_01_49_00.png)

Not sure yet what's going on, but will address soon!

**Comment by athanclark** [comment]
I think the error is stemming from filepath - I changed the `import System.FilePath as FilePath` to `import System.FilePath.Posix as ...`, which keeps tests passing on linux, but in windows, the test is just burning cycles for some reason. It might be the combination of running a virtualbox VM and quickcheck tests, but I'm not sure yet.

**Comment by sjakobi** [comment]
The problem is that what is a valid path on unixy systems like "/home/chris" isn't a valid path on Windows. I think we'll just need to add a bunch of CPP to make a Windows variant of each test.

I have deactivated building the tests on AppVeyor in https://github.com/commercialhaskell/path/commit/160ac322316c1760fb4863068ff2b55e8f8d1bda for now.
