### ISSUE TITLE
Whitespace is allowed in paths.

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/path#41]
```
Prelude> import Path
Prelude Path> :set -XTemplateHaskell
Prelude Path> putStrLn $ toFilePath $(mkAbsDir "/hello\noops")
/hello
oops/
```

**Comment by chrisdone** [comment]
Agree, this is probably always a mistake.

**Comment by NorfairKing** [comment]
In the case of spaces: they should probably be escaped when the path is being parsed and not escaped when stored as a `Path`

**Comment by Ongy** [comment]
I think it should be noted, that newlines are valid characters in paths (on some platforms).

On linux
```
mkdir "hello
oops"
```
Will create a directory that has a newline in its name.
Such paths will (almost) never exist purposly, but technically are valid.

**Comment by NorfairKing** [comment]
aha! I didn't know this. I am undecided as to whether we should leave it possible then.

**Comment by chrisdone** [comment]
I also tested that it's possible, but still it's probably always a mistake.

**Comment by NorfairKing** [comment]
@chrisdone, I agree. It's up to you wether you want to allow it.

**Comment by mrkkrp** [comment]
I think since `\n` is technically correct (like indeed almost any characters) in Unix paths, it should be allowed there. It's not allowed on Windows, so on that OS consturction of `Path` with `\n` in it should fail. I think `filepath` already has functions that will do exactly this sort of check. The practial consequence is that our test suite should have conditional parts that depend on OS.

**Comment by NorfairKing** [comment]
> I think since \n is technically correct (like indeed almost any characters) in Unix paths, it should be allowed there.

Okido!

**Comment by chrisdone** [comment]
I'm okay with that call too. We have an answer to the question, which we didn't have before.

**Comment by sjakobi** [comment]
I like this resolution. :+1:
