### ISSUE TITLE
Make validity-test compatible with GHC-7.10 and GHC-7.8

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/path#80]
This would be nice for checking backwards compatibility and should allow us to remove the `validity` flag which would in turn simplify our CI configs.

This is currently blocked by our dependency on validity which requires `base >= 4.8` and on genvalidity-hspec which [(implicitly) requires `base >= 4.9`](https://github.com/NorfairKing/validity/issues/4).

It looks like validity can easily be made compatible with base-4.7, but genvalidity-hspec relies heavily on `TypeApplications`. We could probably make some ad-hoc helpers with hspec and QuickCheck to replace our use of genvalidity-hspec.

**Comment by NorfairKing** [comment]
Maybe I could split off the parts of `genvalidity-hspec` that require TypeApplications and call the other part `genvalidity-property`. This would solve the problem in this package and further split concerns.
Any feedback?

**Comment by sjakobi** [comment]
@NorfairKing Sounds goot to me! :+1:

**Comment by NorfairKing** [comment]
@sjakobi I had another look, and this isn't as simple as I made it sounds. Tearing up the API like this isn't a good idea, because the boundary that I was going to split on does not align with the TypeApplications-dependency-boundary.

However, I think the validity-tests don't need TypeApplications, so I'm going to have another look at making the validity-tests compatible with earlier GHC versions.

**Comment by NorfairKing** [comment]
On third thought, I'm going to take another look at splitting those packages.

**Comment by NorfairKing** [comment]
It looks like this is going to work. Give me a bit more time.

**Comment by NorfairKing** [comment]
@sjakobi If you'll have a look at https://github.com/NorfairKing/validity/tree/development, I'm making travis configs for every stack lts version starting from lts-2, for the packages that can build with earlier versions. I also split `genvalidity-hspec` into `genvalidity-hspec` and `genvalidity-property` so that `genvalidity-property` doesn't need `TypeApplications`.
If I recall correctly, the `validity-test` of `path` does not require `TypeApplications`, nor any `genvalidity-hspec`-specific features.
This makes me think that it's possible to solve this issue in a somewhat elegant way.

**Comment by sjakobi** [comment]
@NorfairKing Looks promising!

**Comment by NorfairKing** [comment]
I just released the new versions of the `validity` packages. Now it should be possible to resolve this issue by fixing this repo.
