### ISSUE TITLE
Discuss: always prefixing relative paths with a "./" when showing

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/path#99]
If we consider "." as the relative root just like "/" is the absolute root then it sounds consistent to show the relative paths always starting with a "." e.g. "./x/y" instead of "x/y". That also explicitly tells us about the behavior of `parent` i.e. returning "." as the parent of "x".

**Comment by joehillen** [comment]
:-1:

It makes it seem like `parent` would then be useless as it will always `.` instead of something useful.

**Comment by NorfairKing** [comment]
@joehillen , I don't think `parent x/y/z` would return `.`, I think what @harendra-kumar meant is that it should return `x/y`. Is that right @harendra-kumar ? What would you think about that @joehillen ?

**Comment by joehillen** [comment]
@harendra-kumar Could you make a table of input, old output, new output? I'm not understanding what you're proposing.

**Comment by harendra-kumar** [comment]
@NorfairKing that's right. Also, `parent "x"` returns `.`. BTW, I did not propose a change in the behavior of parent here, it is what it is already. The only thing I am proposing here is to change the behavior of the show instance of a relative path. Old behavior:

```
>> $(mkRelDir "x")
"x/"
```

New behavior

```
>> $(mkRelDir "x")
"./x/"
```

That is, we show a relative path to always start with a `.`. It explicitly explains the behavior of `parent "x"` which returns `.`. This format makes better sense after the support for `.` in relative paths.

**Comment by mrkkrp** [comment]
I don't think the current behavior of `parent` needs a more explicit "explanation". This change would make relative paths more verbose and likely a bit confusing. I mean, when we talk about a relative path `x/y`, we expect to see it as `x/y`, no? All in all, I think this one is overkill.

**Comment by NorfairKing** [comment]
I'm actually not opposed. This might ensure that people don't ever use show and `++` to juggle paths.

**Comment by harendra-kumar** [comment]
> I mean, when we talk about a relative path x/y, we expect to see it as x/y, no?

Yes, we have been trained like that. My trigger for this thought was to make relative paths exactly like absolute paths. The way absolute paths are always specified with a `/`, relative paths can be specified with a `.`. For absolute paths `/` is an absolute root, for relative paths `.` is the relative root.

**Comment by joehillen** [comment]
I been quiet about most of the recent breaking changes even though I haven't felt positively about them, but I am strongly against this change: 

1) It's unnecessary to add any extra distinction between absolute and relative paths because absolute paths start with `/` and anything else is relative.

2) Prefixing filepaths with `./` is almost never done in any Unix programming. It feels esoteric. 

3) We're really talking about the internal representation of `Path` because `Abs` and `Rel` are already distinct types. The internal representation could be anything and is totally hidden from users, example it could be a list of directories above. Injecting any number of `./` at the beginning or middle of the filepath does nothing to improve the library's internal workings or usability.

> This might ensure that people don't ever use show and ++ to juggle paths.

@NorfairKing I don't think that's a health attitude to have. Even if we don't agree with using the library in that way, it would be immoral to intentionally try to sabotage programs that do it.

> For absolute paths `/` is an absolute root, for relative paths `.` is the relative root.

@harendra-kumar There is no need for a "relative root". All paths that don't start with `/` are relative. There is no ambiguities about that.

----

If we don't already, I think we should do the *opposite* and scrub all `./` references from paths during construction.

**Comment by NorfairKing** [comment]
@joehillen, thank you for speaking up. I am not trying to argue _for_ the change, but for the record, I have some responses:

> Prefixing filepaths with ./ is almost never done in any Unix programming. It feels esoteric.

You need to use `./~` to remove a file called `~` without removing your home directory.

>  Injecting any number of ./ at the beginning or middle of the filepath does nothing to improve the library's internal workings or usability.

I don't think @harendra-kumar was suggesting changing the internals, just the `show` function.

> it would be immoral to intentionally try to sabotage programs that do it.

Only in the same way that this is immoral: https://stackoverflow.com/questions/2669690/why-does-google-prepend-while1-to-their-json-responses

**Comment by joehillen** [comment]
> You need to use ./~ to remove a file called ~ without removing your home directory.

That's only true in a shell. `~` has no special meaning outside of shells.

**Comment by mrkkrp** [comment]
Since we do not seem to come to an unanimous conclusion on this one, I'll proceed with releasing master in its current form as 0.6.0 (later today or tomorrow).

**Comment by NorfairKing** [comment]
> That's only true in a shell. ~ has no special meaning outside of shells.

Fair enough.
